# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GeolocationApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for GeolocationApp

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  target 'GeolocationAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
